#!/usr/bin/env bash

set -euo pipefail

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
PROJECT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"

WALLPAPER_DIR="$PROJECT_DIR/wallpapers"

# Find all supported image files
mapfile -t wallpapers < <(
    find "$WALLPAPER_DIR" \
        -type f \
        \( \
            -iname "*.jpg" -o \
            -iname "*.jpeg" -o \
            -iname "*.png" -o \
            -iname "*.webp" \
        \)
)

# Exit if no wallpapers found
(( ${#wallpapers[@]} )) || {
    notify-send "Wallpaper" "No wallpapers found."
    exit 1
}

# Choose one at random
CACHE_FILE="$HOME/.cache/midnight-bump-last-wallpaper"

mkdir -p "$(dirname "$CACHE_FILE")"

last_wallpaper=""
[[ -f "$CACHE_FILE" ]] && last_wallpaper=$(cat "$CACHE_FILE")

# Remove last wallpaper from choices if possible
choices=()

for wp in "${wallpapers[@]}"; do
    [[ "$wp" != "$last_wallpaper" ]] && choices+=("$wp")
done

# Fallback if only one wallpaper exists
[[ ${#choices[@]} -eq 0 ]] && choices=("${wallpapers[@]}")

wallpaper="${choices[RANDOM % ${#choices[@]}]}"

echo "$wallpaper" > "$CACHE_FILE"

# Set wallpaper
hyprctl hyprpaper wallpaper "eDP-1,$wallpaper,cover"
echo "$wallpaper"



